Repository Hanaro-JSON/LifeOnHana_FE, pull requests merged in 2025-02, with the labels that each got.

#180 feature/refactor/accountDetailItem
  life_on_hana/components/molecules/AccountDetailItem.tsx
Labels: 🪲Bug

#182 Json 238 feature/refactor/signin
  life_on_hana/app/(routes)/home/lumpsum/otherAccount/page.tsx
  life_on_hana/app/(routes)/signin/mydata/page.tsx
  life_on_hana/app/(routes)/signin/page.tsx
  life_on_hana/app/layout.tsx
  life_on_hana/app/page.tsx
  life_on_hana/assets/invisible.png
  life_on_hana/assets/visible.png
  life_on_hana/components/atoms/Btn.tsx
  life_on_hana/components/atoms/MicroMiniBtn.tsx
  life_on_hana/components/molecules/ConnectBankItem.tsx
  life_on_hana/components/molecules/LoginLabelInput.tsx
  life_on_hana/components/molecules/WhilickItem.tsx
  life_on_hana/types/componentTypes.ts
  life_on_hana/utils/QueryWrapper.tsx
Labels: 🪲Bug, 🎨Publish

#185 [refactor] 🐳 빌드 lint 문제 해결 완료
  life_on_hana/app/(routes)/home/lumpsum/page.tsx
  life_on_hana/components/molecules/LikedLoanProductDetailItem.tsx
  life_on_hana/components/molecules/LineGraph.tsx
  life_on_hana/stories/ConnectBankItem.stories.tsx
  life_on_hana/stories/LoadingIcon.stories.tsx
  life_on_hana/types/dataTypes.ts
  life_on_hana/utils/colors.tsx
Labels: 🪲Bug, 🎨Publish

#187 feature/refactor/NavHeader
  life_on_hana/app/(routes)/column/[id]/page.tsx
  life_on_hana/app/(routes)/home/columns/page.tsx
  life_on_hana/app/(routes)/home/history/page.tsx
  life_on_hana/app/(routes)/home/like/page.tsx
  life_on_hana/app/(routes)/home/lumpsum/page.tsx
  life_on_hana/app/(routes)/home/wallet/deposit/page.tsx
  life_on_hana/app/(routes)/home/wallet/page.tsx
  life_on_hana/components/atoms/Btn.tsx
  life_on_hana/components/molecules/HistoryItem.tsx
Labels: 🪲Bug, 🎨Publish

#188 feature/refactor/whilick
  life_on_hana/api.ts
  life_on_hana/app/(routes)/whilick/page.tsx
  life_on_hana/components/molecules/Nav.tsx
  life_on_hana/components/molecules/NavHeader.tsx
  life_on_hana/components/molecules/WhilickCarousel.tsx
Labels: 🪲Bug, ⛓️API, 🎨Publish

#189 feature/fix/details
  life_on_hana/app/(routes)/home/page.tsx
  life_on_hana/components/molecules/MainSection.tsx
  life_on_hana/stories/SmallWhilickItem.stories.tsx
Labels: 🪲Bug, 🎨Publish

#194 [fix] 🐿️ 로그아웃용 button 태그에 type='button'이 없어 바로 onClick event가 작동하지 않는…
  life_on_hana/components/molecules/LogoHeader.tsx
Labels: 🪲Bug

#196 hotfix/notSignin
  life_on_hana/app/(routes)/home/wallet/page.tsx
  life_on_hana/app/error.tsx
  life_on_hana/app/not-found.tsx
  life_on_hana/assets/notFound.gif
  life_on_hana/components/molecules/LogoHeader.tsx
  life_on_hana/components/molecules/ShortCutBtn.tsx
  life_on_hana/middleware.ts
  life_on_hana/utils/colors.tsx
Labels: 🪲Bug

#200 feature/hotfix/column
  life_on_hana/app/(routes)/column/[id]/page.tsx
  life_on_hana/app/(routes)/column/page.tsx
Labels: 🪲Bug

#203 feature/hotfix/wallet
  life_on_hana/app/(routes)/home/wallet/page.tsx
Labels: 🪲Bug

#205 feature/hotfix/likedProduct
  life_on_hana/api.ts
  life_on_hana/app/(routes)/home/like/page.tsx
  life_on_hana/components/molecules/RecommendItem.tsx
Labels: 🪲Bug

#207 feature/hotfix/homeLikedProduct
  life_on_hana/app/(routes)/home/history/page.tsx
  life_on_hana/app/(routes)/home/page.tsx
  life_on_hana/components/molecules/LineGraph.tsx
  life_on_hana/components/molecules/MainSection.tsx
  life_on_hana/components/molecules/RecommendCarouselItem.tsx
  life_on_hana/utils/formatCurrency.tsx
Labels: 🪲Bug

#209 feature/hotfix/homeWallet
  life_on_hana/app/(routes)/home/wallet/page.tsx
Labels: 🪲Bug

#211 Json 249 hotfix/css and test
  life_on_hana/app/(routes)/column/[id]/page.tsx
  life_on_hana/app/(routes)/home/lumpsum/page.tsx
  life_on_hana/app/(routes)/home/wallet/deposit/finished/page.tsx
  life_on_hana/components/molecules/ColumnRecommendItem.tsx
  life_on_hana/components/molecules/LikedLoanProductDetailItem.tsx
  life_on_hana/components/molecules/RecommendItem.tsx
Labels: 🪲Bug

#212 hotfix/small whilick item
  life_on_hana/api.ts
  life_on_hana/app/(routes)/column/[id]/page.tsx
  life_on_hana/app/(routes)/home/lumpsum/page.tsx
  life_on_hana/app/(routes)/home/wallet/deposit/finished/page.tsx
  life_on_hana/app/(routes)/whilick/page.tsx
  life_on_hana/components/molecules/WhilickItem.tsx
  life_on_hana/types/componentTypes.ts
  life_on_hana/types/dataTypes.ts
Labels: 🪲Bug, ⛓️API, 🎨Publish

#214 feature/hotfix/final
  life_on_hana/app/(routes)/column/[id]/page.tsx
  life_on_hana/app/(routes)/home/history/page.tsx
  life_on_hana/app/(routes)/home/like/page.tsx
  life_on_hana/app/(routes)/home/lumpsum/page.tsx
  life_on_hana/app/(routes)/home/wallet/deposit/page.tsx
  life_on_hana/components/molecules/AccountDetailItem.tsx
  life_on_hana/components/molecules/ArticleAIRecommendDetailItem.tsx
  life_on_hana/components/molecules/HistoryItem.tsx
  life_on_hana/components/molecules/IsLike.tsx
  life_on_hana/components/molecules/RecommendCarouselItem.tsx
  life_on_hana/components/molecules/RecommendItem.tsx
  life_on_hana/middleware.ts
  life_on_hana/stories/RecommendCarouselItem.stories.tsx
  life_on_hana/stories/RecommendItem.stories.tsx
  life_on_hana/types/componentTypes.ts
Labels: 🪲Bug

#215 hotflix/like whilick
  life_on_hana/app/(routes)/home/wallet/page.tsx
  life_on_hana/app/(routes)/whilick/page.tsx
  life_on_hana/assets/signoutBtn.svg
  life_on_hana/components/molecules/Nav.tsx
  life_on_hana/components/molecules/WhilickItem.tsx
  life_on_hana/types/componentTypes.ts
Labels: 🪲Bug, 🎨Publish

#217 hotfix/lumpsum
  life_on_hana/app/(routes)/home/lumpsum/otherAccount/otherAccountFinished/page.tsx
  life_on_hana/app/(routes)/home/lumpsum/otherAccount/page.tsx
  life_on_hana/components/molecules/AccountDetailItem.tsx
  life_on_hana/components/molecules/RecommendCarouselItem.tsx
Labels: 🪲Bug

#219 hotfix/error
  life_on_hana/api.ts
  life_on_hana/app/(routes)/column/[id]/page.tsx
  life_on_hana/app/(routes)/column/page.tsx
  life_on_hana/app/(routes)/home/columns/page.tsx
  life_on_hana/app/(routes)/home/history/page.tsx
  life_on_hana/app/(routes)/home/lumpsum/otherAccount/otherAccountFinished/page.tsx
  life_on_hana/app/(routes)/home/lumpsum/otherAccount/page.tsx
  life_on_hana/app/(routes)/home/lumpsum/page.tsx
  life_on_hana/app/(routes)/home/page.tsx
  life_on_hana/app/(routes)/home/wallet/deposit/finished/page.tsx
  life_on_hana/app/(routes)/home/wallet/page.tsx
  life_on_hana/app/(routes)/signin/mydata/page.tsx
  life_on_hana/app/(routes)/signin/page.tsx
  life_on_hana/components/animation/AnimatedCheck.tsx
  life_on_hana/components/atoms/AdjustBtn.tsx
  life_on_hana/components/atoms/DescriptionDetailItem.tsx
  life_on_hana/components/atoms/MoveToTopBtn.tsx
  life_on_hana/components/atoms/OpenDescriptionItem.tsx
  life_on_hana/components/molecules/AccountDetailItem.tsx
  life_on_hana/components/molecules/ArticleAIRecommendDetailItem.tsx
  life_on_hana/components/molecules/ArticleItem.tsx
  life_on_hana/components/molecules/ColumnRecommendItem.tsx
  life_on_hana/components/molecules/IsLike.tsx
  life_on_hana/components/molecules/LikedAccountProductDetailItem.tsx
  life_on_hana/components/molecules/LikedLifeProductDetail.tsx
  life_on_hana/components/molecules/LikedLoanProductDetailItem.tsx
  life_on_hana/components/molecules/LoginLabelInput.tsx
  life_on_hana/components/molecules/RecommendItem.tsx
  life_on_hana/components/molecules/SearchInput.tsx
  life_on_hana/components/molecules/VerticalBarGraph.tsx
  life_on_hana/lib/auth.ts
  life_on_hana/types/componentTypes.ts
  life_on_hana/types/dataTypes.ts
  life_on_hana/utils/colors.tsx
Labels: 🪲Bug

#222 hotfix/toast class name
  life_on_hana/app/(routes)/column/[id]/page.tsx
  life_on_hana/app/(routes)/column/page.tsx
  life_on_hana/app/(routes)/home/lumpsum/otherAccount/page.tsx
  life_on_hana/app/(routes)/home/lumpsum/page.tsx
  life_on_hana/app/(routes)/home/wallet/page.tsx
  life_on_hana/app/(routes)/signin/page.tsx
  life_on_hana/app/(routes)/whilick/page.tsx
  life_on_hana/app/globals.css
  life_on_hana/components/atoms/CopyClipboardBtn.tsx
  life_on_hana/components/molecules/LogoHeader.tsx
  life_on_hana/components/molecules/WhilickItem.tsx
  life_on_hana/components/ui/toast.tsx
  life_on_hana/hooks/use-toast.ts
  life_on_hana/stories/AdjustBtn.stories.tsx
  life_on_hana/stories/ColumnRecommendItem.stories.tsx
  life_on_hana/stories/MoveToTopBtn.stories.tsx
  life_on_hana/stories/RecommendCarouselItem.stories.tsx
  life_on_hana/stories/RecommendItem.stories.tsx
  life_on_hana/tailwind.config.ts
Labels: 🪲Bug, 🎨Publish

#223 release 0.1.1
  README.md
  life_on_hana/app/(routes)/column/[id]/page.tsx
  life_on_hana/app/(routes)/column/page.tsx
  life_on_hana/app/(routes)/home/lumpsum/otherAccount/page.tsx
  life_on_hana/app/(routes)/home/lumpsum/page.tsx
  life_on_hana/app/(routes)/home/wallet/page.tsx
  life_on_hana/app/(routes)/signin/page.tsx
  life_on_hana/app/(routes)/whilick/page.tsx
  life_on_hana/app/globals.css
  life_on_hana/components/atoms/CopyClipboardBtn.tsx
  life_on_hana/components/molecules/LogoHeader.tsx
  life_on_hana/components/molecules/WhilickItem.tsx
  life_on_hana/components/ui/toast.tsx
  life_on_hana/hooks/use-toast.ts
  life_on_hana/stories/AdjustBtn.stories.tsx
  life_on_hana/stories/ColumnRecommendItem.stories.tsx
  life_on_hana/stories/MoveToTopBtn.stories.tsx
  life_on_hana/stories/RecommendCarouselItem.stories.tsx
  life_on_hana/stories/RecommendItem.stories.tsx
  life_on_hana/tailwind.config.ts
Labels: 🌟Relase

#225 [fix] 🐳 middleware 및 routing 수정
  life_on_hana/app/(routes)/home/wallet/deposit/finished/page.tsx
  life_on_hana/middleware.ts
Labels: 🪲Bug

#226 release 0.1.2
  life_on_hana/app/(routes)/home/wallet/deposit/finished/page.tsx
  life_on_hana/middleware.ts
Labels: 🌟Relase
