Repository Hanaro-JSON/LifeOnHana_FE, pull requests merged in 2025-01, with the labels that each got.

#10 feature/atoms/MicroMiniBtn
  .DS_Store
  life_on_hana/.storybook/main.ts
  life_on_hana/.storybook/preview.ts
  life_on_hana/app/(routes)/signin/page.tsx
  life_on_hana/app/globals.css
  life_on_hana/app/layout.tsx
  life_on_hana/assets/hanaMark.png
  life_on_hana/components/atoms/MicroMiniBtn.tsx
  life_on_hana/stories/Button.stories.ts
  life_on_hana/stories/Button.tsx
  life_on_hana/stories/Configure.mdx
  life_on_hana/stories/Header.stories.ts
  life_on_hana/stories/Header.tsx
  life_on_hana/stories/MicroMiniBtn.stories.tsx
  life_on_hana/stories/Page.stories.ts
  life_on_hana/stories/Page.tsx
  life_on_hana/stories/assets/accessibility.png
  life_on_hana/stories/assets/accessibility.svg
  life_on_hana/stories/assets/addon-library.png
  life_on_hana/stories/assets/assets.png
  life_on_hana/stories/assets/avif-test-image.avif
  life_on_hana/stories/assets/context.png
  life_on_hana/stories/assets/discord.svg
  life_on_hana/stories/assets/docs.png
  life_on_hana/stories/assets/figma-plugin.png
  life_on_hana/stories/assets/github.svg
  life_on_hana/stories/assets/share.png
  life_on_hana/stories/assets/styling.png
  life_on_hana/stories/assets/testing.png
  life_on_hana/stories/assets/theming.png
  life_on_hana/stories/assets/tutorials.svg
  life_on_hana/stories/assets/youtube.svg
  life_on_hana/stories/button.css
  life_on_hana/stories/header.css
  life_on_hana/stories/page.css
  life_on_hana/tailwind.config.ts
Labels: 🎨Publish

#16 [feat] 🐣 Section 추가
  life_on_hana/components/atoms/Section.tsx
  life_on_hana/stories/Section.stories.tsx
Labels: 🎨Publish

#17 feature/atoms/adjustBtn
  life_on_hana/app/globals.css
  life_on_hana/components/atoms/AdjustBtn.tsx
  life_on_hana/stories/AdjustBtn.stories.tsx
Labels: 🎨Publish

#19 [feat] GraphToggle atoms 추가
  life_on_hana/components/atoms/GraphToggle.tsx
  life_on_hana/stories/GraphToggle.stories.tsx
Labels: 🎨Publish

#21 feature/atoms/DescriptionetailItem
  .DS_Store
  life_on_hana/app/(routes)/signin/page.tsx
  life_on_hana/app/globals.css
  life_on_hana/assets/exitBtn.svg
  life_on_hana/components/atoms/DescriptionDetailItem.tsx
  life_on_hana/stories/DescriptionDetailItem.tsx.stories.tsx
Labels: 🎨Publish

#23 feature/atoms/OpenDescriptionItem
  life_on_hana/app/(routes)/signin/page.tsx
  life_on_hana/assets/openDescriptionItem.svg
  life_on_hana/components/atoms/AdjustBtn.tsx
  life_on_hana/components/atoms/DescriptionDetailItem.tsx
  life_on_hana/components/atoms/OpenDescriptionItem.tsx
  life_on_hana/components/atoms/Section.tsx
  life_on_hana/stories/DescriptionDetailItem.tsx.stories.tsx
  life_on_hana/stories/OpenDescriptionItem.stories.tsx
  life_on_hana/stories/Section.stories.tsx
Labels: 🎨Publish

#25 feature/atoms/MoveToTopBtn
  life_on_hana/assets/moveToTopBtn.svg
  life_on_hana/components/atoms/Btn.tsx
  life_on_hana/components/atoms/MoveToTopBtn.tsx
  life_on_hana/stories/MoveToTopBtn.stories.tsx
Labels: 🎨Publish

#28 feature/atoms/copyClipboardBtn
  life_on_hana/app/globals.css
  life_on_hana/app/layout.tsx
  life_on_hana/assets/CopyClipboardBtnImg.svg
  life_on_hana/components/atoms/CopyClipboardBtn.tsx
  life_on_hana/components/ui/toast.tsx
  life_on_hana/components/ui/toaster.tsx
  life_on_hana/hooks/use-toast.ts
  life_on_hana/package.json
  life_on_hana/pnpm-lock.yaml
  life_on_hana/stories/CopyClipboardBtn.stories.tsx
Labels: 🎨Publish

#30 [feat] 🐣 ShortsAutoToggle 추가
  life_on_hana/assets/pause.svg
  life_on_hana/assets/play.svg
  life_on_hana/components/atoms/ShortsAutoToggle.tsx
  life_on_hana/stories/ShortsAutoToggle.stories.tsx
Labels: 🎨Publish

#29 feature/atoms/MoveToBackBtn
  life_on_hana/assets/moveToBackBtn.svg
  life_on_hana/components/atoms/Btn.tsx
  life_on_hana/components/atoms/DescriptionDetailItem.tsx
  life_on_hana/components/atoms/MoveToBackBtn.tsx
  life_on_hana/components/atoms/MoveToTopBtn.tsx
  life_on_hana/components/ui/button.tsx
  life_on_hana/package.json
  life_on_hana/pnpm-lock.yaml
Labels: 🎨Publish

#33 feature/atoms/MiniBtn
  life_on_hana/components/atoms/MiniBtn.tsx
  life_on_hana/pnpm-lock.yaml
  life_on_hana/stories/MiniBtn.stories.tsx
Labels: 🎨Publish

#34 [feat] 🐣 CarouselSection 추가
  life_on_hana/assets/arrow-left.svg
  life_on_hana/assets/arrow-right.svg
  life_on_hana/components/atoms/CarouselSection.tsx
  life_on_hana/stories/CarouselSection.stories.tsx
Labels: 🎨Publish

#36 feature/molecules/AssetManageWayItem
  life_on_hana/components/molecules/AssetManageWayItem.tsx
  life_on_hana/components/molecules/Btn.tsx
  life_on_hana/public/assets/adjust.svg
  life_on_hana/public/assets/culture.svg
  life_on_hana/public/assets/invest.svg
  life_on_hana/public/assets/managing.svg
  life_on_hana/public/assets/product.svg
  life_on_hana/public/assets/realEstate.svg
  life_on_hana/public/assets/rebalancing.svg
  life_on_hana/public/assets/trip.svg
  life_on_hana/public/file.svg
  life_on_hana/public/globe.svg
  life_on_hana/public/next.svg
  life_on_hana/public/vercel.svg
  life_on_hana/public/window.svg
  life_on_hana/stories/AssetManageWayItem.stories.tsx
Labels: 🎨Publish

#41 feature/molecules/ArticleAIRecommendDetailItem
  life_on_hana/components/molecules/ArticleAIRecommendDetailItem.tsx
  life_on_hana/stories/ArticleAIRecommendDetailItem.stories.tsx
Labels: 🎨Publish

#42 feature/molecules/SearchInput
  life_on_hana/assets/removeAllBtn.svg
  life_on_hana/assets/searchBtn.svg
  life_on_hana/components/molecules/SearchInput.tsx
  life_on_hana/stories/SearchInput.stories.tsx
Labels: 🎨Publish

#46 feature/molecules/LikedAccountProductDetailItem
  life_on_hana/components/molecules/LikedAccountProductDetailItem.tsx
  life_on_hana/stories/LikedAccountProductDetailItem.stories.tsx
Labels: 🎨Publish

#47 feature/molecules/historyItem
  life_on_hana/assets/DEPOSIT.svg
  life_on_hana/assets/EDUCATION.svg
  life_on_hana/assets/ETC.svg
  life_on_hana/assets/FIXED_EXPENSE.svg
  life_on_hana/assets/FOOD.svg
  life_on_hana/assets/HEALTH.svg
  life_on_hana/assets/HOBBY.svg
  life_on_hana/assets/INTEREST.svg
  life_on_hana/assets/SNACK.svg
  life_on_hana/assets/TRAVEL.svg
  life_on_hana/components/molecules/HistoryItem.tsx
  life_on_hana/stories/HistoryItem.stories.tsx
  life_on_hana/utils/convertTimeFormat.tsx
Labels: 🎨Publish

#51 feature/molecules/Nav
  life_on_hana/app/(routes)/column/page.tsx
  life_on_hana/app/(routes)/home/page.tsx
  life_on_hana/app/(routes)/whilick/page.tsx
  life_on_hana/app/layout.tsx
  life_on_hana/app/page.tsx
  life_on_hana/components/molecules/Nav.tsx
  life_on_hana/public/assets/column.svg
  life_on_hana/public/assets/column_clicked.svg
  life_on_hana/public/assets/home.svg
  life_on_hana/public/assets/home_clicked.svg
  life_on_hana/public/assets/whilick.svg
  life_on_hana/public/assets/whilick_clicked.svg
Labels: 🎨Publish

#50 feature/molecules/LikedLoanProductDetailItem
  life_on_hana/components/molecules/LikedLoanProductDetailItem.tsx
  life_on_hana/stories/LikedLoanProductDetailItem.stories.tsx
Labels: 🎨Publish

#55 feature/molecules/login lable input
  life_on_hana/app/(routes)/signin/page.tsx
  life_on_hana/assets/logo.png
  life_on_hana/assets/logo.svg
  life_on_hana/assets/logoDetail.png
  life_on_hana/assets/logoText.png
  life_on_hana/assets/logoText.svg
  life_on_hana/components/atoms/Btn.tsx
  life_on_hana/components/molecules/HistoryItem.tsx
  life_on_hana/components/molecules/LoginLabelInput.tsx
  life_on_hana/stories/Btn.stories.tsx
  life_on_hana/stories/LoginLabelInput.stories.tsx
Labels: 🎨Publish

#58 feature/molecules/ColumnMainImgItem
  life_on_hana/app/(routes)/column/page.tsx
  life_on_hana/app/(routes)/home/page.tsx
  life_on_hana/app/(routes)/whilick/page.tsx
  life_on_hana/app/page.tsx
  life_on_hana/components/molecules/ColumnMainImgItem.tsx
  life_on_hana/components/molecules/Nav.tsx
  life_on_hana/public/assets/column_main_culture.svg
  life_on_hana/public/assets/column_main_hobby.svg
  life_on_hana/public/assets/column_main_inheritanceGift.svg
  life_on_hana/public/assets/column_main_investment.svg
  life_on_hana/public/assets/column_main_realEstate.svg
  life_on_hana/public/assets/column_main_travel.svg
  life_on_hana/stories/ColumnMainImgItem.stories.tsx
Labels: 🎨Publish

#53 feature/molecules/ShortCutBtn
  life_on_hana/assets/KeyboardArrowRight.svg
  life_on_hana/components/molecules/ShortCutBtn.tsx
  life_on_hana/stories/ShortCutBtn.stories.tsx
Labels: 🎨Publish

#59 feature/molecules/ArticleItem
  life_on_hana/assets/HeartNo.svg
  life_on_hana/assets/HeartYes.svg
  life_on_hana/components/molecules/ArticleItem.tsx
  life_on_hana/stories/ArticleItem.stories.tsx
  life_on_hana/utils/formatDate.tsx
Labels: 🎨Publish

#66 feature/molecules/SmallWhilickItem
  life_on_hana/app/(routes)/whilick/page.tsx
  life_on_hana/assets/smallWhilick_title.svg
  life_on_hana/components/molecules/ColumnMainImgItem.tsx
  life_on_hana/components/molecules/SmallWhilickItem.tsx
  life_on_hana/package.json
  life_on_hana/pnpm-lock.yaml
  life_on_hana/public/assets/column_whilick_inheritanceGift.svg
  life_on_hana/public/assets/smallWhilick_culture.svg
  life_on_hana/public/assets/smallWhilick_hobby.svg
  life_on_hana/public/assets/smallWhilick_inheritanceGift.svg
  life_on_hana/public/assets/smallWhilick_investment.svg
  life_on_hana/public/assets/smallWhilick_realEstate.svg
  life_on_hana/public/assets/smallWhilick_travel.svg
  life_on_hana/stories/SmallWhilickItem.stories.tsx
Labels: 🎨Publish

#67 feature/molecules/recommend item
  life_on_hana/components/atoms/Section.tsx
  life_on_hana/components/molecules/LoginLabelInput.tsx
  life_on_hana/components/molecules/RecommendItem.tsx
  life_on_hana/stories/RecommendItem.stories.tsx
Labels: 🎨Publish

#62 feature/molecules/IsLike
  life_on_hana/components/molecules/IsLike.tsx
  life_on_hana/stories/IsLike.stories.tsx
Labels: 🎨Publish

#64 feature/molecules/ConnectBankItem
  life_on_hana/assets/HanaBankLogo.svg
  life_on_hana/assets/KakaoBankLogo.svg
  life_on_hana/assets/MydataCheckNo.svg
  life_on_hana/assets/MydataCheckYes.svg
  life_on_hana/assets/NaverBankLogo.svg
  life_on_hana/assets/NonghyupBankLogo.svg
  life_on_hana/assets/ShinhanBankLogo.svg
  life_on_hana/assets/TossBankLogo.svg
  life_on_hana/assets/WooriBankLogo.svg
  life_on_hana/components/molecules/ConnectBankItem.tsx
  life_on_hana/stories/ConnectBankItem.stories.tsx
Labels: 🎨Publish

#68 feature/molecules/AccountDetailItem
  life_on_hana/components/molecules/AccountDetailItem.tsx
  life_on_hana/stories/AccountDetailItem.stories.tsx
Labels: 🎨Publish

#70 feature/molecules/ColumnRecommendItem
  life_on_hana/app/(routes)/column/page.tsx
  life_on_hana/components/molecules/ColumnRecommendItem.tsx
  life_on_hana/components/molecules/SmallWhilickItem.tsx
  life_on_hana/public/assets/column_recommend_culture.svg
  life_on_hana/public/assets/column_recommend_hobby.svg
  life_on_hana/public/assets/column_recommend_inheritanceGift.svg
  life_on_hana/public/assets/column_recommend_investment.svg
  life_on_hana/public/assets/column_recommend_realEstate.svg
  life_on_hana/public/assets/column_recommend_travel.svg
  life_on_hana/stories/AssetManageWayItem.stories.tsx
  life_on_hana/stories/Btn.stories.tsx
  life_on_hana/stories/ColumnMainImgItem.stories.tsx
  life_on_hana/stories/ColumnRecommendItem.stories.tsx
  life_on_hana/stories/LumpSumBtn.stories.tsx
  life_on_hana/stories/MiniBtn.stories.tsx
  life_on_hana/stories/SearchInput.stories.tsx
  life_on_hana/stories/SmallWhilickItem.stories.tsx
Labels: 🎨Publish

#72 fix/molecules/LikedLoanProductDetailItem
  life_on_hana/assets/X.svg
  life_on_hana/components/molecules/LikedLoanProductDetailItem.tsx
  life_on_hana/stories/LikedLoanProductDetailItem.stories.tsx
Labels: 🎨Publish

#73 fix/molecules/LikedAccountProductDetailItem
  life_on_hana/components/molecules/LikedAccountProductDetailItem.tsx
  life_on_hana/stories/LikedAccountProductDetailItem.stories.tsx
Labels: 🎨Publish

#75 fix/molecules/LikedLoanProductDetailItem
  life_on_hana/stories/LikedLoanProductDetailItem.stories.tsx
Labels: 🎨Publish

#74 fix/molecules/ArticleAIRecommendDetailItem
  life_on_hana/components/molecules/ArticleAIRecommendDetailItem.tsx
  life_on_hana/stories/ArticleAIRecommendDetailItem.stories.tsx
Labels: 🎨Publish

#76 fix/molecules/DetailItem
  life_on_hana/components/molecules/ArticleAIRecommendDetailItem.tsx
  life_on_hana/components/molecules/LikedAccountProductDetailItem.tsx
  life_on_hana/components/molecules/LikedLoanProductDetailItem.tsx
Labels: 🎨Publish

#78 feature/molecules/recommendCarouselItem
  life_on_hana/components/atoms/CarouselSection.tsx
  life_on_hana/components/atoms/Section.tsx
  life_on_hana/components/molecules/RecommendCarouselItem.tsx
  life_on_hana/stories/CarouselSection.stories.tsx
  life_on_hana/stories/RecommendCarouselItem.stories.tsx
  life_on_hana/stories/Section.stories.tsx
Labels: 🎨Publish

#80 [fix] 은행이름 API에 맞게 통일
  life_on_hana/components/molecules/AccountDetailItem.tsx
  life_on_hana/components/molecules/ConnectBankItem.tsx
  life_on_hana/stories/AccountDetailItem.stories.tsx
  life_on_hana/stories/ConnectBankItem.stories.tsx
Labels: 🎨Publish

#81 fix/molecules/AccountDetailItem
  life_on_hana/components/molecules/AccountDetailItem.tsx
Labels: 🎨Publish

#82 feature/molecules/MainSection
  life_on_hana/app/(routes)/home/page.tsx
  life_on_hana/components/atoms/Section.tsx
  life_on_hana/components/molecules/MainSection.tsx
  life_on_hana/components/molecules/Nav.tsx
  life_on_hana/public/assets/mainSectionImgA.svg
  life_on_hana/public/assets/mainSectionImgB.svg
  life_on_hana/public/assets/mainSectionImgC.svg
  life_on_hana/public/assets/mainSectionImgD.svg
  life_on_hana/public/assets/mainSectionImgE.svg
  life_on_hana/public/assets/mainSectionTitleA.svg
  life_on_hana/public/assets/mainSectionTitleB.svg
  life_on_hana/public/assets/mainSectionTitleC.svg
  life_on_hana/public/assets/mainSectionTitleD.svg
  life_on_hana/public/assets/mainSectionTitleE.svg
  life_on_hana/stories/MainSection.stories.tsx
Labels: 🎨Publish

#85 feature/pages/Onboarding
  life_on_hana/app/(routes)/signin/page.tsx
  life_on_hana/app/layout.tsx
  life_on_hana/app/page.tsx
  life_on_hana/components/atoms/AdjustBtn.tsx
  life_on_hana/components/atoms/Btn.tsx
  life_on_hana/components/atoms/CarouselSection.tsx
  life_on_hana/components/atoms/GraphToggle.tsx
  life_on_hana/components/atoms/MiniBtn.tsx
  life_on_hana/components/atoms/Section.tsx
  life_on_hana/components/atoms/ShortsAutoToggle.tsx
  life_on_hana/components/molecules/AccountDetailItem.tsx
  life_on_hana/components/molecules/ArticleAIRecommendDetailItem.tsx
  life_on_hana/components/molecules/ArticleItem.tsx
  life_on_hana/components/molecules/AssetManageWayItem.tsx
  life_on_hana/components/molecules/ColumnMainImgItem.tsx
  life_on_hana/components/molecules/ColumnRecommendItem.tsx
  life_on_hana/components/molecules/ConnectBankItem.tsx
  life_on_hana/components/molecules/HistoryItem.tsx
  life_on_hana/components/molecules/IsLike.tsx
  life_on_hana/components/molecules/LikedAccountProductDetailItem.tsx
  life_on_hana/components/molecules/LikedLoanProductDetailItem.tsx
  life_on_hana/components/molecules/LoginLabelInput.tsx
  life_on_hana/components/molecules/LumpSumBtn.tsx
  life_on_hana/components/molecules/MainSection.tsx
  life_on_hana/components/molecules/Nav.tsx
  life_on_hana/components/molecules/RecommendCarouselItem.tsx
  life_on_hana/components/molecules/RecommendItem.tsx
  life_on_hana/components/molecules/SearchInput.tsx
  life_on_hana/components/molecules/ShortCutBtn.tsx
  life_on_hana/components/molecules/SmallWhilickItem.tsx
  life_on_hana/public/assets/hanaXjson.svg
  life_on_hana/public/assets/logoText_white.svg
  life_on_hana/public/assets/logo_json.svg
  life_on_hana/public/assets/logo_white.svg
  life_on_hana/types/componentTypes.ts
Labels: 🎨Publish

#86 fix/molecules/SearchInput
  life_on_hana/components/molecules/SearchInput.tsx
Labels: 🪲Bug, 🎨Publish

#90 feature/pages/column
  life_on_hana/app/(routes)/column/page.tsx
  life_on_hana/components/molecules/ArticleItem.tsx
  life_on_hana/components/molecules/SearchInput.tsx
  life_on_hana/next.config.ts
  life_on_hana/public/assets/column_color.svg
Labels: 🎨Publish

#92 fix/pages/column
  life_on_hana/app/(routes)/column/page.tsx
Labels: 🎨Publish

#93 feature/molecules/barGraph
  life_on_hana/components/molecules/BarGraph.tsx
  life_on_hana/components/ui/card.tsx
  life_on_hana/components/ui/chart.tsx
  life_on_hana/package.json
  life_on_hana/pnpm-lock.yaml
  life_on_hana/stories/BarGraph.stories.tsx
  life_on_hana/utils/convertEnumtoString.tsx
Labels: 🎨Publish

#94 feature/pages/Signin-Mydata
  life_on_hana/app/(routes)/signin/mydata/page.tsx
  life_on_hana/app/layout.tsx
  life_on_hana/components/molecules/ConnectBankItem.tsx
  life_on_hana/types/componentTypes.ts
Labels: 🎨Publish

#104 feature/pages/home/lumpsum
  life_on_hana/app/(routes)/column/detail/page.tsx
  life_on_hana/app/(routes)/column/page.tsx
  life_on_hana/app/(routes)/home/lumpsum/page.tsx
  life_on_hana/app/(routes)/home/page.tsx
  life_on_hana/app/(routes)/signin/page.tsx
  life_on_hana/app/globals.css
  life_on_hana/assets/arrow-right-white.svg
  life_on_hana/assets/signoutBtn.svg
  life_on_hana/components/atoms/Btn.tsx
  life_on_hana/components/atoms/CarouselSection.tsx
  life_on_hana/components/atoms/Section.tsx
  life_on_hana/components/molecules/BarGraph.tsx
  life_on_hana/components/molecules/FullImgCarousel.tsx
  life_on_hana/components/molecules/LogoHeader.tsx
  life_on_hana/components/molecules/LumpSumBtn.tsx
  life_on_hana/components/molecules/MainSection.tsx
  life_on_hana/components/molecules/NavHeader.tsx
  life_on_hana/components/molecules/RecommendCarouselColumn.tsx
  life_on_hana/components/molecules/RecommendCarouselItem.tsx
  life_on_hana/components/molecules/ShortCutBtn.tsx
  life_on_hana/components/ui/chart.tsx
  life_on_hana/hooks/useData.tsx
  life_on_hana/package.json
  life_on_hana/pnpm-lock.yaml
  life_on_hana/types/componentTypes.ts
Labels: 🎨Publish

#105 feature/pages/home/like
  life_on_hana/app/(routes)/home/like/page.tsx
  life_on_hana/components/molecules/LikedAccountProductDetailItem.tsx
  life_on_hana/components/molecules/LikedLifeProductDetail.tsx
  life_on_hana/components/molecules/LikedLoanProductDetailItem.tsx
  life_on_hana/components/molecules/RecommendItem.tsx
  life_on_hana/stories/LikedLifeProductDetailItem.stories.tsx
  life_on_hana/types/componentTypes.ts
Labels: 🎨Publish

#111 feature/pages/homeWalletDepositFinished
  life_on_hana/app/(routes)/home/wallet/deposit/finished/page.tsx
  life_on_hana/components/animation/AnimatedCheck.tsx
Labels: 🎨Publish

#112 fix/pages/homeLike
  life_on_hana/app/(routes)/home/like/page.tsx
  life_on_hana/components/molecules/LikedAccountProductDetailItem.tsx
  life_on_hana/components/molecules/LikedLifeProductDetail.tsx
  life_on_hana/components/molecules/LikedLoanProductDetailItem.tsx
  life_on_hana/components/molecules/RecommendItem.tsx
  life_on_hana/stories/LikedAccountProductDetailItem.stories.tsx
  life_on_hana/stories/LikedLifeProductDetailItem.stories.tsx
  life_on_hana/stories/LikedLoanProductDetailItem.stories.tsx
Labels: 🎨Publish

#113 fix/pages/column
  life_on_hana/app/(routes)/column/page.tsx
  life_on_hana/components/molecules/ArticleItem.tsx
  life_on_hana/components/molecules/SearchInput.tsx
  life_on_hana/types/componentTypes.ts
Labels: 🎨Publish

#114 animation 추가
  life_on_hana/app/(routes)/column/page.tsx
  life_on_hana/components/animation/AnimatedCheck.tsx
Labels: 🎨Publish

#115 column 페이지 글씨 크기 조절 추가
  life_on_hana/app/(routes)/column/[id]/page.tsx
  life_on_hana/components/atoms/AdjustBtn.tsx
  life_on_hana/types/componentTypes.ts
Labels: 🎨Publish

#117 feature/pages/home-columns
  life_on_hana/app/(routes)/column/page.tsx
  life_on_hana/app/(routes)/home/columns/page.tsx
  life_on_hana/assets/whilickIcon.svg
  life_on_hana/components/molecules/ArticleItem.tsx
  life_on_hana/components/molecules/FullImgCarousel.tsx
  life_on_hana/components/molecules/IsLike.tsx
  life_on_hana/components/molecules/RecommendCarouselColumn.tsx
  life_on_hana/components/molecules/RecommendCarouselItem.tsx
  life_on_hana/components/molecules/ShortCutBtn.tsx
  life_on_hana/components/molecules/SmallWhilickItem.tsx
  life_on_hana/components/molecules/WhilickCarousel.tsx
  life_on_hana/types/dataTypes.ts
  life_on_hana/utils/convertEnumtoString.tsx
Labels: 🎨Publish

#122 fix/pages/whilick
  life_on_hana/app/(routes)/home/page.tsx
  life_on_hana/app/(routes)/whilick/page.tsx
  life_on_hana/components/atoms/AdjustBtn.tsx
  life_on_hana/components/molecules/WhilickItem.tsx
  life_on_hana/types/componentTypes.ts
Labels: 🪲Bug, 🎨Publish

#123 feature/fetch/homeProducts
  life_on_hana/api.ts
  life_on_hana/app/(routes)/home/like/page.tsx
  life_on_hana/components/molecules/LikedAccountProductDetailItem.tsx
  life_on_hana/components/molecules/LikedLoanProductDetailItem.tsx
  life_on_hana/components/molecules/RecommendItem.tsx
  life_on_hana/types/componentTypes.ts
  life_on_hana/types/dataTypes.ts
Labels: ⛓️API, 🎨Publish

#125 feature/fetch/column
  life_on_hana/api.ts
  life_on_hana/app/(routes)/column/[id]/page.tsx
  life_on_hana/app/(routes)/column/page.tsx
  life_on_hana/app/(routes)/home/columns/page.tsx
  life_on_hana/app/(routes)/home/page.tsx
  life_on_hana/components/molecules/ArticleItem.tsx
  life_on_hana/components/molecules/LikedLoanProductDetailItem.tsx
  life_on_hana/next.config.ts
  life_on_hana/stories/ArticleItem.stories.tsx
  life_on_hana/types/componentTypes.ts
  life_on_hana/types/dataTypes.ts
Labels: ⛓️API, 🎨Publish

#128 feature/fetch/homeWalletDeposit
  life_on_hana/api.ts
  life_on_hana/app/(routes)/home/wallet/deposit/page.tsx
  life_on_hana/assets/KBBankLogo.svg
  life_on_hana/components/molecules/AccountDetailItem.tsx
Labels: ⛓️API, 🎨Publish

#131 feature/fetch/homeWalletDepositFinished
  life_on_hana/api.ts
  life_on_hana/app/(routes)/home/wallet/deposit/finished/page.tsx
  life_on_hana/app/(routes)/home/wallet/deposit/page.tsx
  life_on_hana/components/molecules/AccountDetailItem.tsx
  life_on_hana/types/componentTypes.ts
Labels: ⛓️API, 🎨Publish

#130 feature/pages/home/history
  life_on_hana/app/(routes)/home/columns/page.tsx
  life_on_hana/app/(routes)/home/history/page.tsx
  life_on_hana/assets/month-left.svg
  life_on_hana/assets/month-right.svg
  life_on_hana/assets/shopingBag.svg
  life_on_hana/components/molecules/HistoryItem.tsx
  life_on_hana/components/molecules/VerticalBarGraph.tsx
  life_on_hana/types/componentTypes.ts
  life_on_hana/types/dataTypes.ts
Labels: 🎨Publish

#133 feature/fetch/signin
  life_on_hana/actions/myauth.ts
  life_on_hana/api.ts
  life_on_hana/app/(routes)/home/page.tsx
  life_on_hana/app/(routes)/signin/page.tsx
  life_on_hana/app/(routes)/whilick/page.tsx
  life_on_hana/app/page.tsx
  life_on_hana/hooks/useData.tsx
  life_on_hana/lib/auth.ts
Labels: ⛓️API

#135 feature/fetch/column[id]
  life_on_hana/api.ts
  life_on_hana/app/(routes)/column/[id]/page.tsx
  life_on_hana/components/molecules/ArticleAIRecommendDetailItem.tsx
  life_on_hana/components/molecules/ArticleItem.tsx
  life_on_hana/next.config.ts
  life_on_hana/types/componentTypes.ts
  life_on_hana/types/dataTypes.ts
Labels: ⛓️API, 🎨Publish

#138 feature/fetch/logout
  life_on_hana/actions/myauth.ts
  life_on_hana/api.ts
  life_on_hana/app/(routes)/signin/page.tsx
  life_on_hana/app/layout.tsx
  life_on_hana/components/molecules/LogoHeader.tsx
  life_on_hana/hooks/useData.tsx
Labels: ⛓️API

#139 [feat] 🐣 상품 좋아요 기능 추가 및 api연결
  life_on_hana/api.ts
  life_on_hana/app/(routes)/column/[id]/page.tsx
  life_on_hana/app/(routes)/column/page.tsx
  life_on_hana/app/(routes)/home/like/page.tsx
  life_on_hana/components/molecules/LikedAccountProductDetailItem.tsx
  life_on_hana/components/molecules/LikedLifeProductDetail.tsx
  life_on_hana/components/molecules/LikedLoanProductDetailItem.tsx
  life_on_hana/components/molecules/RecommendItem.tsx
  life_on_hana/components/molecules/ShortCutBtn.tsx
  life_on_hana/types/componentTypes.ts
Labels: ⛓️API, 🎨Publish

#141 feature/fetch/columnColumnid
  life_on_hana/app/(routes)/column/[id]/page.tsx
  life_on_hana/components/atoms/AdjustBtn.tsx
  life_on_hana/components/molecules/AccountDetailItem.tsx
  life_on_hana/components/molecules/ArticleAIRecommendDetailItem.tsx
  life_on_hana/components/molecules/ArticleItem.tsx
  life_on_hana/components/molecules/IsLike.tsx
  life_on_hana/components/molecules/LikedAccountProductDetailItem.tsx
  life_on_hana/components/molecules/LikedLifeProductDetail.tsx
  life_on_hana/components/molecules/LikedLoanProductDetailItem.tsx
  life_on_hana/components/molecules/SearchInput.tsx
  life_on_hana/types/componentTypes.ts
Labels: ⛓️API, 🎨Publish

#145 feature/fetch/homeColumns
  life_on_hana/api.ts
  life_on_hana/app/(routes)/home/columns/page.tsx
  life_on_hana/app/(routes)/home/page.tsx
  life_on_hana/components/molecules/SmallWhilickItem.tsx
  life_on_hana/components/molecules/WhilickCarousel.tsx
  life_on_hana/types/componentTypes.ts
Labels: ⛓️API, 🎨Publish

#147 feature/refactor/column
  life_on_hana/app/(routes)/column/[id]/page.tsx
  life_on_hana/app/(routes)/column/page.tsx
  life_on_hana/components/molecules/ArticleAIRecommendDetailItem.tsx
  life_on_hana/stories/ArticleAIRecommendDetailItem.stories.tsx
  life_on_hana/stories/DescriptionDetailItem.tsx.stories.tsx
  life_on_hana/types/componentTypes.ts
Labels: 🎨Publish

#149 feature/pages/splash
  life_on_hana/app/(routes)/signin/mydata/page.tsx
  life_on_hana/app/clientLayout.tsx
  life_on_hana/app/globals.css
  life_on_hana/app/layout.tsx
  life_on_hana/app/page.tsx
  life_on_hana/assets/KBBankLogo.svg
  life_on_hana/assets/loadingIcon.svg
  life_on_hana/components/atoms/LoadingIcon.tsx
  life_on_hana/components/atoms/MicroMiniBtn.tsx
  life_on_hana/components/molecules/ConnectBankItem.tsx
  life_on_hana/components/molecules/LogoHeader.tsx
  life_on_hana/hooks/useData.tsx
  life_on_hana/public/assets/culture.svg
  life_on_hana/public/assets/home.svg
  life_on_hana/public/assets/home_clicked.svg
  life_on_hana/public/assets/realEstate.svg
  life_on_hana/public/assets/trip.svg
  life_on_hana/stories/LoadingIcon.stories.tsx
Labels: 🪲Bug, 🎨Publish

#152 feature/refactorcolumnAi
  life_on_hana/app/(routes)/column/[id]/page.tsx
  life_on_hana/components/atoms/LoadingIcon.tsx
  life_on_hana/components/molecules/ArticleAIRecommendDetailItem.tsx
  life_on_hana/types/componentTypes.ts
Labels: 🎨Publish

#153 feature/fetch/home
  life_on_hana/api.ts
  life_on_hana/app/(routes)/home/page.tsx
  life_on_hana/components/molecules/FullImgCarousel.tsx
  life_on_hana/components/molecules/RecommendCarouselItem.tsx
  life_on_hana/hooks/useData.tsx
  life_on_hana/lib/auth.ts
Labels: ⛓️API, 🎨Publish

#158 feature/fetch/homeProducts
  life_on_hana/api.ts
  life_on_hana/app/(routes)/home/like/page.tsx
Labels: ⛓️API

#160 feature/refactoer/columnId
  life_on_hana/app/(routes)/column/[id]/page.tsx
Labels: 🎨Publish

#161 feature/fetch/home wallet
  life_on_hana/api.ts
  life_on_hana/app/(routes)/home/wallet/page.tsx
  life_on_hana/hooks/useData.tsx
Labels: ⛓️API

#162 feature/fetch/whilick
  life_on_hana/app/(routes)/column/[id]/page.tsx
  life_on_hana/app/(routes)/home/columns/page.tsx
  life_on_hana/app/(routes)/whilick/page.tsx
  life_on_hana/components/atoms/WhilickDownSvg.tsx
  life_on_hana/components/molecules/ArticleAIRecommendDetailItem.tsx
  life_on_hana/components/molecules/SmallWhilickItem.tsx
  life_on_hana/components/molecules/WhilickCarousel.tsx
  life_on_hana/components/molecules/WhilickItem.tsx
  life_on_hana/types/dataTypes.ts
Labels: ⛓️API, 🎨Publish

#167 fix/fetch/whilick
  life_on_hana/api.ts
  life_on_hana/app/(routes)/column/[id]/page.tsx
  life_on_hana/app/(routes)/whilick/page.tsx
  life_on_hana/app/(routes)/whilickPractice/page.tsx
  life_on_hana/app/page.tsx
  life_on_hana/components/molecules/MainSection.tsx
  life_on_hana/components/molecules/Nav.tsx
  life_on_hana/components/molecules/WhilickItem.tsx
  life_on_hana/next.config.ts
  life_on_hana/types/dataTypes.ts
Labels: 🪲Bug, ⛓️API

#169 feature/fetch/home
  life_on_hana/api.ts
  life_on_hana/app/(routes)/home/columns/page.tsx
  life_on_hana/app/(routes)/home/history/page.tsx
  life_on_hana/app/(routes)/home/page.tsx
  life_on_hana/components/atoms/CarouselSection.tsx
  life_on_hana/components/molecules/BarGraph.tsx
  life_on_hana/components/molecules/FullImgCarousel.tsx
  life_on_hana/components/molecules/RecommendCarouselItem.tsx
  life_on_hana/components/molecules/VerticalBarGraph.tsx
  life_on_hana/types/componentTypes.ts
Labels: 🪲Bug

#170 feature/fetch/homeHistory
  life_on_hana/api.ts
  life_on_hana/app/(routes)/column/page.tsx
  life_on_hana/app/(routes)/home/columns/page.tsx
  life_on_hana/app/(routes)/home/history/page.tsx
  life_on_hana/app/(routes)/home/like/page.tsx
  life_on_hana/app/(routes)/home/page.tsx
  life_on_hana/components/molecules/SmallWhilickItem.tsx
  life_on_hana/components/molecules/VerticalBarGraph.tsx
  life_on_hana/components/molecules/WhilickCarousel.tsx
  life_on_hana/types/dataTypes.ts
Labels: 🪲Bug, ⛓️API, 🎨Publish

#172 feature/lumpsum
  life_on_hana/api.ts
  life_on_hana/app/(routes)/home/lumpsum/otherAccount/otherAccountFinished/page.tsx
  life_on_hana/app/(routes)/home/lumpsum/otherAccount/page.tsx
  life_on_hana/app/(routes)/home/lumpsum/page.tsx
  life_on_hana/components/molecules/AccountDetailItem.tsx
  life_on_hana/utils/colors.tsx
Labels: 🪲Bug, ⛓️API, 🎨Publish

#173 feature/design
  life_on_hana/app/(routes)/home/columns/page.tsx
  life_on_hana/app/(routes)/home/history/page.tsx
  life_on_hana/app/(routes)/home/lumpsum/otherAccount/page.tsx
  life_on_hana/app/(routes)/home/lumpsum/page.tsx
  life_on_hana/app/(routes)/home/page.tsx
  life_on_hana/app/(routes)/home/wallet/page.tsx
  life_on_hana/app/globals.css
  life_on_hana/app/page.tsx
  life_on_hana/components/atoms/Btn.tsx
  life_on_hana/components/atoms/CopyClipboardBtn.tsx
  life_on_hana/components/atoms/GraphToggle.tsx
  life_on_hana/components/atoms/MicroMiniBtn.tsx
  life_on_hana/components/molecules/AccountDetailItem.tsx
  life_on_hana/components/molecules/ArticleItem.tsx
  life_on_hana/components/molecules/AssetManageWayItem.tsx
  life_on_hana/components/molecules/BarGraph.tsx
  life_on_hana/components/molecules/FullImgCarousel.tsx
  life_on_hana/components/molecules/HistoryItem.tsx
  life_on_hana/components/molecules/LikedAccountProductDetailItem.tsx
  life_on_hana/components/molecules/LikedLifeProductDetail.tsx
  life_on_hana/components/molecules/LikedLoanProductDetailItem.tsx
  life_on_hana/components/molecules/LogoHeader.tsx
  life_on_hana/components/molecules/LumpSumBtn.tsx
  life_on_hana/components/molecules/MainSection.tsx
  life_on_hana/components/molecules/NavHeader.tsx
  life_on_hana/components/molecules/RecommendCarouselItem.tsx
  life_on_hana/components/molecules/RecommendItem.tsx
  life_on_hana/components/molecules/ShortCutBtn.tsx
  life_on_hana/components/molecules/VerticalBarGraph.tsx
  life_on_hana/components/molecules/WhilickCarousel.tsx
Labels: 🎨Publish

#175 feature/refactor/column
  life_on_hana/app/(routes)/column/[id]/page.tsx
  life_on_hana/app/(routes)/column/page.tsx
Labels: 🪲Bug, 🎨Publish

#177 20250127 회의 수정 사항 반영
  life_on_hana/api.ts
  life_on_hana/app/(routes)/column/[id]/page.tsx
  life_on_hana/app/(routes)/home/columns/page.tsx
  life_on_hana/app/(routes)/home/history/page.tsx
  life_on_hana/app/(routes)/home/lumpsum/page.tsx
  life_on_hana/app/(routes)/home/page.tsx
  life_on_hana/app/(routes)/home/wallet/page.tsx
  life_on_hana/app/(routes)/signin/page.tsx
  life_on_hana/components/atoms/CopyClipboardBtn.tsx
  life_on_hana/components/atoms/Section.tsx
  life_on_hana/components/molecules/ArticleItem.tsx
  life_on_hana/components/molecules/HistoryItem.tsx
  life_on_hana/components/molecules/LikedAccountProductDetailItem.tsx
  life_on_hana/components/molecules/LikedLifeProductDetail.tsx
  life_on_hana/components/molecules/LumpSumBtn.tsx
  life_on_hana/components/molecules/RecommendCarouselItem.tsx
  life_on_hana/components/molecules/SmallWhilickItem.tsx
  life_on_hana/components/molecules/WhilickCarousel.tsx
  life_on_hana/utils/colors.tsx
Labels: 🪲Bug, ⛓️API, 🎨Publish

#179 feature/refactor/column
  life_on_hana/api.ts
  life_on_hana/app/(routes)/column/[id]/page.tsx
  life_on_hana/components/molecules/ColumnRecommendItem.tsx
  life_on_hana/public/assets/column_recommend_loan.svg
Labels: 🪲Bug, 🎨Publish
